# 2 Vectors Basics

## Introduction to vectors

### Scalars 
* Scalars denote numbers 
* denoted by lowercase symbols like a, b 
* ex: denote weight, temp, blood pressure etc

### Vectors
* Vector is an ordered list of numbers 
* denoted by bolded roman letters, have arrow on top
* ex: $\vec{v}$
* 2 characterstics: 
  * dimensionality: the number of elements in the vector
  * orientation: column orientation or row orientation

In [ ]:
import numpy as np
vectorAsArray = np.array([1,2,3,4,5]) # neither a row nor a column vector

# row vector - 5D row vector
rowVector = np.array([[1,2,3,4,5]])

# column vector - 5D column vector
columnVector = np.array([[1], [2], [3], [4], [5]])

## Vector arithmetic

## Addition and Subtraction
* They should have the same dimensions

In [6]:
import numpy as np

a = np.array([20, 40, 60])
b = np.array([10, 20, 30])
c = np.array([5, 10, 15, 20]) # a and c have different dimensions - so cannot be added or subtracted

# Addition
print(a + b)

# Subtraction
print(a - b)

# multiplication
print(a * b)

# division
print(a / b)

scalar = 2
print(scalar * a)


[30 60 90]
[10 20 30]
[ 200  800 1800]
[2. 2. 2.]
[ 40  80 120]
